#include "pch.h"
#include "include/Core.h"


BOOST_CLASS_EXPORT(ItemH);
BOOST_CLASS_EXPORT(ProjectH);
BOOST_CLASS_EXPORT(CompH);
BOOST_CLASS_EXPORT(LayerH);
BOOST_CLASS_EXPORT(Collection2H);
BOOST_CLASS_EXPORT(CollectionItemH);
BOOST_CLASS_EXPORT(FootageH);
BOOST_CLASS_EXPORT(StreamRefH);
BOOST_CLASS_EXPORT(EffectRefH);